name: notes_reminder_app
description: "Notes & Reminders App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  flutter_native_timezone: ^2.0.0
  lottie: ^3.3.1
  http: ^1.1.0

  shared_preferences: ^2.3.2
  audioplayers: ^6.5.0
  intl: ^0.20.2
  provider: ^6.1.2
  flutter_tts: ^4.2.3
  speech_to_text: ^7.3.0
  share_plus: ^10.0.2
  connectivity_plus: ^6.1.5

  home_widget: ^0.5.0


  local_auth: ^2.1.7

  cryptography: ^2.7.0
  encrypt: ^5.0.1
  flutter_secure_storage: ^9.0.0
  file_picker: ^6.1.1
  pdf: ^3.10.5

  path_provider: ^2.1.5

  json_annotation: ^4.8.1

  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2

  firebase_crashlytics: ^5.0.1
  firebase_analytics: ^12.0.1

  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter
  uuid: ^4.5.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/lottie/mascot.json
    - assets/lottie/mascot2.json
    - assets/lottie/mascot3.json
