name: notes_reminder_app
description: "Notes & Reminders App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  flutter_native_timezone: ^2.0.0
  lottie: ^3.3.1
  http: ^1.5.0

  flutter_colorpicker: ^1.1.0

  flutter_slidable: ^4.0.1

  shared_preferences: ^2.5.3
  audioplayers: ^6.5.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  flutter_tts: ^4.2.3
  speech_to_text: ^7.3.0
  share_plus: ^10.1.4
  connectivity_plus: ^6.1.5

  home_widget: ^0.5.0


  local_auth: ^2.3.0

  logger: ^2.0.2

  cryptography: ^2.7.0
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.4
  file_picker: ^6.2.1
  pdf: ^3.11.3

  image_picker: ^1.2.0

  path_provider: ^2.1.5

  json_annotation: ^4.9.0

  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2

  firebase_crashlytics: ^5.0.1
  firebase_analytics: ^12.0.1

  googleapis: ^14.0.0
  google_sign_in: ^6.3.0
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  fuse: ^0.0.99

  alarm_domain:
    path: alarm_domain
  alarm_data:
    path: alarm_data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter
  build_runner: ^2.8.0
  json_serializable: ^6.11.1
  connectivity_plus_platform_interface: ^2.0.1
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/lottie/mascot.json
    - assets/lottie/mascot2.json
    - assets/lottie/mascot3.json
