name: notes_reminder_app
description: "Notes & Reminders App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  lottie: ^3.3.1
  http: ^1.2.2
  shared_preferences: ^2.3.2
  audioplayers: ^6.5.0
  intl: ^0.18.1
  flutter_tts: ^4.2.3
  provider: ^6.0.5
  speech_to_text: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/mascot.json
    - assets/lottie/mascot2.json
    - assets/lottie/mascot3.json
