name: alarm_data
description: Data layer for notes reminder app
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.7.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  alarm_domain:
    path: ../alarm_domain

  file_picker: ^workspace
  pdf: ^workspace
  path_provider: ^workspace
  uuid: ^workspace
  encrypt: ^workspace
  cryptography: ^workspace
  flutter_secure_storage: ^workspace
  shared_preferences: ^workspace

dev_dependencies:
  build_runner: ^workspace
  json_serializable: ^workspace
