name: alarm_data
description: Data layer implementations for alarm app
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  alarm_domain:
    path: ../alarm_domain
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  encrypt: ^5.0.3
  cryptography: ^2.7.0
  file_picker: ^6.2.1
  pdf: ^3.11.3
  path_provider: ^2.1.5
  uuid: ^4.5.1
  json_annotation: ^4.9.0
  flutter_local_notifications: ^19.4.1

dev_dependencies:
  build_runner: ^2.8.0
  json_serializable: ^6.11.1
  flutter_test:
    sdk: flutter
