name: alarm_data
description: Data layer for notes reminder app
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  alarm_domain:
    path: ../alarm_domain
  file_picker: ^6.2.1
  pdf: ^3.11.3
  path_provider: ^2.1.5
  uuid: ^4.5.1
  encrypt: ^5.0.3
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
