name: Build Android APK
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4

        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - name: Install Android SDK 36 and NDK 27
        run: |
          yes | sdkmanager "platforms;android-36" "build-tools;36.0.0" "ndk;27.0.12077973"
      - run: flutter clean
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
