name: Build Android APK
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: $HOME/android-sdk
    steps:

      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5

        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - name: Install Android CMD tools
        run: |
          ANDROID_SDK_ROOT=$HOME/android-sdk
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -o cmdtools.zip
          unzip -q cmdtools.zip
          mv cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
      - name: Install required SDK packages
        run: yes | sdkmanager "platforms;android-36" "build-tools;36.0.0" "ndk;27.0.12077973"
      - run: flutter clean
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
