name: Dependency Check

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
      - run: flutter clean
      - run: flutter pub get
      - name: Check for outdated packages
        id: outdated
        run: |
          flutter pub outdated --exit-code > outdated.log
        continue-on-error: true
      - name: Check for outdated packages in sub-packages
        id: outdated_packages
        run: |
          status=0
          for dir in alarm_data alarm_domain; do
            echo "Checking $dir"
            (cd $dir && flutter pub outdated --exit-code > outdated.log) || status=1
          done
          exit $status
        continue-on-error: true
      - name: Dry-run major version upgrades
        id: upgrade
        run: |
          flutter pub upgrade --major-versions --dry-run > upgrade.log
        continue-on-error: true
      - name: Dry-run major version upgrades in sub-packages
        id: upgrade_packages
        run: |
          status=0
          for dir in alarm_data alarm_domain; do
            echo "Upgrading $dir"
            (cd $dir && flutter pub upgrade --major-versions --dry-run > upgrade.log) || status=1
          done
          exit $status
        continue-on-error: true
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pub-report
          path: |
            outdated.log
            upgrade.log
            alarm_data/outdated.log
            alarm_data/upgrade.log
            alarm_domain/outdated.log
            alarm_domain/upgrade.log
      - name: Fail if updates or conflicts found
        if: steps.outdated.outcome == 'failure' || steps.outdated_packages.outcome == 'failure' || steps.upgrade.outcome == 'failure' || steps.upgrade_packages.outcome == 'failure'
        run: |
          echo "Dependency updates or conflicts detected."
          exit 1
