name: PR Debug Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: $HOME/android-sdk
    steps:
      - uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: beta
      - name: Install Android cmdline-tools
        run: |
          ANDROID_SDK_ROOT=$HOME/android-sdk
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -o cmdtools.zip
          unzip -q cmdtools.zip
          mv cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
      - name: Install required SDK packages
        run: yes | sdkmanager "platforms;android-36" "build-tools;36.0.0" "ndk;27.0.12077973"
      - name: Cache pub packages
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            ~/.android
            /usr/local/lib/android/sdk
          key: ${{ runner.os }}-android-${{ hashFiles('android/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-android-
      - run: flutter clean
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: flutter build apk --debug
